<?php

use \charlestang\commonlib\qcloud\cos\Directory;
use \charlestang\commonlib\qcloud\cos\File;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-07-22 at 22:54:32.
 */
class DirectoryTest extends PHPUnit_Framework_TestCase
{

    /**
     * 用于执行测试用例的 bucket 名
     */
    const UNIT_TEST_BUCKET = 'unit_test';

    protected function setUp()
    {

    }

    protected function tearDown()
    {

    }

    public function testCreateRecursively()
    {
        $directory = new Directory(self::UNIT_TEST_BUCKET, '/test_directory/create_recursively/');
        $directory->createRecursively();
        $this->assertAttributeEquals('create_recursively', 'name', $directory);
        $this->assertAttributeEquals('/test_directory/create_recursively/', 'fullPath', $directory);
        $this->assertTrue($directory->isLoaded());
    }

    public function testUploadFile()
    {
        $filePath  = __DIR__ . '/test_upload.txt';
        $directory = new Directory(self::UNIT_TEST_BUCKET, '/test_directory/create_recursively/');
        $file      = $directory->uploadFile($filePath);
        $this->assertTrue($file instanceof File);
        $this->assertAttributeEquals('test_upload.txt', 'name', $file);
        $this->assertAttributeEquals('/test_directory/create_recursively/test_upload.txt', 'fullPath', $file);
    }

}
