<?php

use \charlestang\commonlib\qcloud\cos\File;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-07-24 at 23:10:03.
 */
class FileTest extends PHPUnit_Framework_TestCase
{

    /**
     * 用于执行测试用例的 bucket 名
     */
    const UNIT_TEST_BUCKET = 'unit_test';

    protected function setUp()
    {

    }

    protected function tearDown()
    {

    }

    public function testLoad()
    {

    }

    /**
     * @covers charlestang\commonlib\qcloud\cos\File::updateWith
     */
    public function testUpdateWith()
    {
        $filePath = __DIR__ . '/test_upload.txt';
        $file     = new File(self::UNIT_TEST_BUCKET, '/test_directory/create_recursively/test_upload.txt');
        $result   = $file->updateWith($filePath);
        $this->assertTrue($result);
        $randFile = '/test_directory/create_recursively/not_exists' . rand(0, 999) . '.txt';
        $file2    = new File(self::UNIT_TEST_BUCKET, $randFile);
        $result2  = $file2->updateWith($filePath);
        $this->assertTrue($result2);
    }
}
